version: '3'
services:
  main:
    container_name: main-server
    build: ./main
    depends_on:
      - db
    ports:
      - 8000:8000
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: brica-main-development
      POSTGRES_HOST: db
     
  coins:
    container_name: coins-server
    build: ./coins
    ports:
      - 8001:8001

  notifications:
    container_name: notifications-server
    build: ./notifications
    ports:
      - 8002:8002

  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: brica-main-development
      POSTGRES_HOST: db
    
volumes: 
  pgdata: {}



